# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-08 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentTransition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.IntegerField()),
                ('patient', models.IntegerField()),
                ('doctor', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('scheduled_time', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
